class ColorPalette:

    def __init__(self):
        self.colors = ['aqua', 'aquamarine',
                       'beige', 'bisque', 'black', 'blanchedalmond', 'blue',
                       'blueviolet', 'brown', 'burlywood', 'cadetblue',
                       'chartreuse', 'chocolate', 'coral', 'cornflowerblue',
                       'cornsilk', 'crimson', 'cyan', 'darkblue', 'darkcyan',
                       'darkgoldenrod', 'darkgreen',
                       'darkkhaki', 'darkolivegreen', 'darkorange',
                       'darkorchid', 'darkred', 'darksalmon', 'darkseagreen',
                       'darkslateblue', 'darkslategray', 'darkslategrey',
                       'darkturquoise', 'darkviolet', 'deeppink', 'deepskyblue',
                       'dimgray', 'dimgrey', 'dodgerblue', 'firebrick',
                       'floralwhite', 'forestgreen', 'fuchsia', 'gainsboro',
                       'ghostwhite', 'gold', 'goldenrod', 'gray', 'grey', 'green',
                       'greenyellow', 'honeydew', 'hotpink', 'indigo',
                       'ivory', 'khaki', 'lavender', 'lavenderblush', 'lightyellow', 'lime',
                       'magenta', 'maroon', 'mistyrose', 'moccasin', 'navajowhite', 'navy',
                       'oldlace', 'olive', 'olivedrab', 'orange', 'orangered',
                       'orchid', 'palegoldenrod', 'palegreen', 'paleturquoise',
                       'palevioletred', 'papayawhip', 'peachpuff', 'peru', 'pink',
                       'plum', 'powderblue', 'purple', 'red', 'rosybrown',
                       'royalblue', 'rebeccapurple', 'saddlebrown', 'salmon',
                       'sandybrown', 'seagreen', 'seashell', 'sienna', 'silver',
                       'skyblue', 'slateblue', 'slategrey', 'snow',
                       'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato',
                       'turquoise', 'violet', 'wheat', 'white', 'whitesmoke',
                       'yellow']
